//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string addres { get; set; }
        public string Notes { get; set; }
        public string phone { get; set; }
        public string Company { get; set; }
        public string email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Image { get; set; }
    }
}
